name: Good First Issue
description: Suggest a simple contribution to improve our product
title: "[GFI]: "
labels: [good first issue]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a good first issue for this project! Please fill out the following template to help the maintainers and the community understand your suggestion.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of the contribution
      placeholder: "Describe the contribution"
    validations:
      required: true
  - type: textarea
    id: comments-questions
    attributes:
      label: Comments / questions
      description: Any comments or questions relating the contribution.
      placeholder: "Comments / questions"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Andreasgdp/Wishing-Plan/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
