name: Security Vulnerability
description: File a vulnerability report
title: "[Vulnerability]: "
labels: [MAJOR]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this vulnerability report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the vulnerability
      placeholder: "Describe the vulnerability"
    validations:
      required: true
  - type: textarea
    id: possible-fix
    attributes:
      label: Possible Fix / Recommendation
      description: Descripe a possible fix for the vulnerability or give a recommendation
      placeholder: "Describe a possible fix or recommendation"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: attatchments
    attributes:
      label: Attatchments
      description: Please attatch images and videos/GIFs or a link to show what and where the vulnerability is.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Andreasgdp/Wishing-Plan/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
