name: Format and lint check

on: [pull_request]

permissions:
  pull-requests: write
  contents: write

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: ESLint Reviewdog Check
        uses: reviewdog/action-eslint@v1.18.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: 'src/'
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.15
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier check
        run: pnpm format:check
