name: Tests
on:
  push:
    branches: ["master"]
  # pull_request all branches
  pull_request:
    branches: ["*"]

permissions:
  pull-requests: write
  contents: write

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.15
      - name: Install dependencies
        run: pnpm install
      - name: Run Unit Tests
        run: pnpm test:ci
        env:
          SKIP_ENV_VALIDATION: true
